In [1]:
import numpy as np

In [4]:
n = np.zeros((4,3))

In [5]:
n

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
o = np.ones((2,4))

In [7]:
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
e = np.empty((4,5))

In [11]:
e

array([[2.76194811e-316, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 4.24514012e+175],
       [5.30276956e+180, 1.57076922e-076, 4.57664832e-071,
        3.45775135e-086, 3.35910285e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 6.86712591e+169],
       [2.35861033e+180, 1.43465726e-051, 6.23012460e-038,
        5.19190290e-144, 1.50008929e+248]])

In [12]:
l =[3,55,234,6,1,63,21]

In [13]:
np.array(l)

array([  3,  55, 234,   6,   1,  63,  21])

In [20]:
x=np.arange(1,50,5)

In [21]:
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [22]:
x.shape

(10,)

In [25]:
x.reshape(2,5)

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46]])

In [26]:
x.dtype

dtype('int32')

In [27]:
x.ndim

1

In [33]:
ar = np.array([[2,3,4],
               [7,6,9]])

In [34]:
ar*ar

array([[ 4,  9, 16],
       [49, 36, 81]])

In [35]:
ar-ar

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
ar+ar

array([[ 4,  6,  8],
       [14, 12, 18]])

In [37]:
ar2 = np.array([[1,2,3],[4,6,2]])

In [38]:
ar*ar2

array([[ 2,  6, 12],
       [28, 36, 18]])

In [39]:
ar+5

array([[ 7,  8,  9],
       [12, 11, 14]])

In [40]:
ar**2


array([[ 4,  9, 16],
       [49, 36, 81]], dtype=int32)

In [41]:
ar/2

array([[1. , 1.5, 2. ],
       [3.5, 3. , 4.5]])

In [42]:
ar**0.5


array([[1.41421356, 1.73205081, 2.        ],
       [2.64575131, 2.44948974, 3.        ]])

In [43]:
ar>ar2


array([[ True,  True,  True],
       [ True, False,  True]])

In [44]:
r = np.random.randn(4)

In [45]:
r

array([ 0.6594301 , -0.77048182, -0.8978479 ,  1.13438976])

In [47]:
r>0

array([ True, False, False,  True])

In [49]:
r[r>0]

array([0.6594301 , 1.13438976])

In [52]:
ar[1][2]

9

In [53]:
ar3 = np.array([1,4,6,2,7])

In [54]:
ar3[3]

2

In [55]:
ran = np.random.randn(5,5)

In [56]:
ran

array([[-1.51142857,  1.16198989, -0.28194666, -1.09462792, -1.32041958],
       [-0.76228349,  0.49458754,  0.34253927, -0.89486868, -0.94837465],
       [-0.22359137, -0.01400418,  0.7335017 ,  0.55706474,  0.83237223],
       [-0.88863932,  0.69101681, -0.41807201, -0.28172347, -0.10627294],
       [-0.38399366, -0.78645003, -0.81985864,  0.13958963, -0.75891546]])

In [57]:
ran[1:-1,1:-1]=0

In [58]:
ran

array([[-1.51142857,  1.16198989, -0.28194666, -1.09462792, -1.32041958],
       [-0.76228349,  0.        ,  0.        ,  0.        , -0.94837465],
       [-0.22359137,  0.        ,  0.        ,  0.        ,  0.83237223],
       [-0.88863932,  0.        ,  0.        ,  0.        , -0.10627294],
       [-0.38399366, -0.78645003, -0.81985864,  0.13958963, -0.75891546]])

In [59]:
ran[1:5]

array([[-0.76228349,  0.        ,  0.        ,  0.        , -0.94837465],
       [-0.22359137,  0.        ,  0.        ,  0.        ,  0.83237223],
       [-0.88863932,  0.        ,  0.        ,  0.        , -0.10627294],
       [-0.38399366, -0.78645003, -0.81985864,  0.13958963, -0.75891546]])

In [60]:
ran[1:5,1:3]

array([[ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [-0.78645003, -0.81985864]])

In [61]:
ran

array([[-1.51142857,  1.16198989, -0.28194666, -1.09462792, -1.32041958],
       [-0.76228349,  0.        ,  0.        ,  0.        , -0.94837465],
       [-0.22359137,  0.        ,  0.        ,  0.        ,  0.83237223],
       [-0.88863932,  0.        ,  0.        ,  0.        , -0.10627294],
       [-0.38399366, -0.78645003, -0.81985864,  0.13958963, -0.75891546]])

In [62]:
ran[ran>0]

array([1.16198989, 0.83237223, 0.13958963])

In [63]:
[ran>0]

[array([[False,  True, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False,  True],
        [False, False, False, False, False],
        [False, False, False,  True, False]])]

In [64]:
np.sqrt(ar)

array([[1.41421356, 1.73205081, 2.        ],
       [2.64575131, 2.44948974, 3.        ]])

In [65]:
np.power(ar,3)

array([[  8,  27,  64],
       [343, 216, 729]], dtype=int32)

In [66]:
np.maximum(ar,ar2)

array([[2, 3, 4],
       [7, 6, 9]])

In [68]:
np.where(ar>5,"G",ar)

array([['2', '3', '4'],
       ['G', 'G', 'G']], dtype='<U11')

In [70]:
ar.cumsum()

array([ 2,  5,  9, 16, 22, 31], dtype=int32)

In [71]:
ar.cumprod()

array([   2,    6,   24,  168, 1008, 9072], dtype=int32)

In [72]:
ar.mean()

5.166666666666667

In [73]:
ar.sort()

In [74]:
ar

array([[2, 3, 4],
       [6, 7, 9]])

In [75]:
y = ar>6

In [76]:
y.sum()

2

In [77]:
y.any()

True

In [78]:
y.all()

False

In [79]:
y

array([[False, False, False],
       [False,  True,  True]])

In [80]:
np.unique(ar)

array([2, 3, 4, 6, 7, 9])

In [87]:
np.save("testar",ar)

In [90]:
np.savez("testarm",ar,ar2)

In [91]:
ld= np.load("testar.npy")

In [92]:
ld

array([[2, 3, 4],
       [6, 7, 9]])

In [94]:
p = np.random.randn(3,3)

In [95]:
q = np.random.randn(3,3)

In [96]:
p.dot(q)

array([[ 1.96022658,  2.90802451, -1.45439366],
       [ 0.88730241,  0.95604536, -1.38795138],
       [-0.37858677,  2.63796576, -0.76105461]])

In [97]:
p.trace()

1.717111181159094

In [99]:
q.transpose()

array([[-0.40021214,  0.0358726 , -0.86966323],
       [-2.56611249, -1.12487328, -0.51636583],
       [ 0.88848264, -0.26395262,  0.42164128]])

In [102]:
d= np.random.seed(3)

In [104]:
np.random.normal(size=(2,2))

array([[ 1.78862847,  0.43650985],
       [ 0.09649747, -1.8634927 ]])

In [105]:
np.random.uniform(size=(3,3))

array([[0.89294695, 0.89629309, 0.12558531],
       [0.20724288, 0.0514672 , 0.44080984],
       [0.02987621, 0.45683322, 0.64914405]])

In [107]:
np.random.gamma((4,6))

array([5.77524843, 3.295597  ])