In [2]:
import numpy as np

In [4]:
n = np.zeros((4,3))

In [5]:
n

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
o = np.ones((2,4))

In [7]:
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
e = np.empty((4,5))

In [11]:
e

array([[2.76194811e-316, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 4.24514012e+175],
       [5.30276956e+180, 1.57076922e-076, 4.57664832e-071,
        3.45775135e-086, 3.35910285e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 6.86712591e+169],
       [2.35861033e+180, 1.43465726e-051, 6.23012460e-038,
        5.19190290e-144, 1.50008929e+248]])

In [12]:
l =[3,55,234,6,1,63,21]

In [13]:
np.array(l)

array([  3,  55, 234,   6,   1,  63,  21])

In [20]:
x=np.arange(1,50,5)

In [21]:
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [22]:
x.shape

(10,)

In [25]:
x.reshape(2,5)

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46]])

In [26]:
x.dtype

dtype('int32')

In [27]:
x.ndim

1

In [44]:
r = np.random.randn(4)

In [45]:
r

array([ 0.6594301 , -0.77048182, -0.8978479 ,  1.13438976])

In [64]:
np.sqrt(ar)

array([[1.41421356, 1.73205081, 2.        ],
       [2.64575131, 2.44948974, 3.        ]])

In [65]:
np.power(ar,3)

array([[  8,  27,  64],
       [343, 216, 729]], dtype=int32)

In [66]:
np.maximum(ar,ar2)

array([[2, 3, 4],
       [7, 6, 9]])

In [68]:
np.where(ar>5,"G",ar)

array([['2', '3', '4'],
       ['G', 'G', 'G']], dtype='<U11')

In [70]:
ar.cumsum()

array([ 2,  5,  9, 16, 22, 31], dtype=int32)

In [71]:
ar.cumprod()

array([   2,    6,   24,  168, 1008, 9072], dtype=int32)

In [72]:
ar.mean()

5.166666666666667

In [73]:
ar.sort()

In [74]:
ar

array([[2, 3, 4],
       [6, 7, 9]])

In [75]:
y = ar>6

In [76]:
y.sum()

2

In [77]:
y.any()

True

In [78]:
y.all()

False

In [79]:
y

array([[False, False, False],
       [False,  True,  True]])

In [80]:
np.unique(ar)

array([2, 3, 4, 6, 7, 9])

In [87]:
np.save("testar",ar)

In [90]:
np.savez("testarm",ar,ar2)

In [91]:
ld= np.load("testar.npy")

In [92]:
ld

array([[2, 3, 4],
       [6, 7, 9]])

In [94]:
p = np.random.randn(3,3)

In [95]:
q = np.random.randn(3,3)

In [96]:
p.dot(q)

array([[ 1.96022658,  2.90802451, -1.45439366],
       [ 0.88730241,  0.95604536, -1.38795138],
       [-0.37858677,  2.63796576, -0.76105461]])

In [97]:
p.trace()

1.717111181159094

In [99]:
q.transpose()

array([[-0.40021214,  0.0358726 , -0.86966323],
       [-2.56611249, -1.12487328, -0.51636583],
       [ 0.88848264, -0.26395262,  0.42164128]])

In [102]:
d= np.random.seed(3)

In [104]:
np.random.normal(size=(2,2))

array([[ 1.78862847,  0.43650985],
       [ 0.09649747, -1.8634927 ]])

In [105]:
np.random.uniform(size=(3,3))

array([[0.89294695, 0.89629309, 0.12558531],
       [0.20724288, 0.0514672 , 0.44080984],
       [0.02987621, 0.45683322, 0.64914405]])

In [107]:
np.random.gamma((4,6))

array([5.77524843, 3.295597  ])

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [5]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [6]:
np.random.randint(5,size=(2,3))

array([[2, 1, 0],
       [1, 2, 0]])

In [9]:
ar3 = np.array([2,5,26,1,7,8])

In [10]:
ar3.astype(float)

array([ 2.,  5., 26.,  1.,  7.,  8.])

In [11]:
ar3.resize((3,6))

In [12]:
ar3

array([[ 2,  5, 26,  1,  7,  8],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [13]:
np.append(ar3,(3,542,5,6))

array([  2,   5,  26,   1,   7,   8,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   3, 542,   5,   6])

In [15]:
np.add(ar3,7)

array([[ 9, 12, 33,  8, 14, 15],
       [ 7,  7,  7,  7,  7,  7],
       [ 7,  7,  7,  7,  7,  7]])

In [16]:
np.subtract(ar3,3)

array([[-1,  2, 23, -2,  4,  5],
       [-3, -3, -3, -3, -3, -3],
       [-3, -3, -3, -3, -3, -3]])

In [18]:
np.multiply(ar3,3)

array([[ 6, 15, 78,  3, 21, 24],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [19]:
np.divide(ar3,3)

array([[0.66666667, 1.66666667, 8.66666667, 0.33333333, 2.33333333,
        2.66666667],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [20]:
np.power(ar3,4)

array([[    16,    625, 456976,      1,   2401,   4096],
       [     0,      0,      0,      0,      0,      0],
       [     0,      0,      0,      0,      0,      0]], dtype=int32)

In [21]:
np.sin(ar3)

array([[ 0.90929743, -0.95892427,  0.76255845,  0.84147098,  0.6569866 ,
         0.98935825],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]])

In [22]:
np.cos(ar3)

array([[-0.41614684,  0.28366219,  0.64691932,  0.54030231,  0.75390225,
        -0.14550003],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ]])

In [23]:
np.tan(ar3)

array([[-2.18503986, -3.38051501,  1.17875355,  1.55740772,  0.87144798,
        -6.79971146],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]])

In [27]:
np.abs(ar3)

array([[ 2,  5, 26,  1,  7,  8],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [31]:
np.ceil(ar3)

array([[ 2.,  5., 26.,  1.,  7.,  8.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [32]:
np.floor(ar3)

array([[ 2.,  5., 26.,  1.,  7.,  8.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [33]:
np.round(ar3
        )

array([[ 2,  5, 26,  1,  7,  8],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [34]:
np.min(ar3)

0

In [35]:
np.max(ar3)

26

In [36]:
np.var(ar3)

38.08950617283951

In [37]:
np.std(ar3)

6.171669642231308