# Assignment: Ionosphere Data Problem

### Dataset Description: 

This radar data was collected by a system in Goose Bay, Labrador. This system consists of a phased array of 16 high-frequency antennas with a total transmitted power on the order of 6.4 kilowatts. See the paper for more details. The targets were free electrons in the ionosphere. "Good" radar returns are those showing evidence of some type of structure in the ionosphere. "Bad" returns are those that do not; their signals pass through the ionosphere.

Received signals were processed using an autocorrelation function whose arguments are the time of a pulse and the pulse number. There were 17 pulse numbers for the Goose Bay system. Instances in this databse are described by 2 attributes per pulse number, corresponding to the complex values returned by the function resulting from the complex electromagnetic signal.

### Attribute Information:

- All 34 are continuous
- The 35th attribute is either "good" or "bad" according to the definition summarized above. This is a binary classification task.

 <br><br>

<table border="1"  cellpadding="6">
	<tbody>
        <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Data Set Characteristics:&nbsp;&nbsp;</b></p></td>
		<td><p class="normal">Multivariate</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Instances:</b></p></td>
		<td><p class="normal">351</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Area:</b></p></td>
		<td><p class="normal">Physical</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">
    <tbody>
        <tr>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Attribute Characteristics:</b></p></td>
            <td><p class="normal">Integer,Real</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Number of Attributes:</b></p></td>
            <td><p class="normal">34</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Date Donated</b></p></td>
            <td><p class="normal">N/A</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">	
    <tbody>
    <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Associated Tasks:</b></p></td>
		<td><p class="normal">Classification</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Missing Values?</b></p></td>
		<td><p class="normal">N/A</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Web Hits:</b></p></td>
		<td><p class="normal">N/A</p></td>
	</tr>
    </tbody>
    </table>

### WORKFLOW :
- Load Data
- Check Missing Values ( If Exist ; Fill each record with mean of its feature ) or any usless column.
- Shuffle the data if needed.
- Standardized the Input Variables. **Hint**: Centeralized the data
- Split into 60 and 40 ratio.
- Encode labels.
- Model : 1 hidden layers including 16 unit.
- Compilation Step (Note : Its a Binary problem , select loss , metrics according to it)
- Train the Model with Epochs (100).
- If the model gets overfit tune your model by changing the units , No. of layers , epochs , add dropout layer or add Regularizer according to the need .
- Prediction should be > **92%**
- Evaluation Step
- Prediction


# Load Data:
[Click Here to Download DataSet](https://github.com/ramsha275/ML_Datasets/blob/main/ionosphere_data.csv)

In [1]:
import pandas as pd
df= pd.read_csv('ionosphere_data.csv')

# Checking Missing Values 

In [2]:
df.isnull().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

# Standardizing input and splitting it into 60:40 ratio

In [4]:
from sklearn.model_selection import train_test_split

x = df.values[:, :-1]
y = df.values[:, -1]

x_train, x_test , y_train, y_test = train_test_split(x,y, test_size= 0.40, random_state= 7)
x_train

array([[ 1.     ,  0.     ,  0.50112, ...,  0.10562,  0.60674, -0.0809 ],
       [ 1.     ,  0.     ,  1.     , ..., -1.     ,  1.     , -1.     ],
       [ 1.     ,  0.     ,  1.     , ..., -0.20101,  0.83867, -0.20766],
       ...,
       [ 1.     ,  0.     ,  1.     , ..., -1.     ,  1.     , -1.     ],
       [ 1.     ,  0.     ,  1.     , ...,  1.     ,  1.     ,  1.     ],
       [ 1.     ,  0.     ,  1.     , ...,  0.35294,  1.     ,  0.23529]])

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train[:,1:] = scaler.fit_transform(x_train[:,1:])
x_test[:,1:]  = scaler.transform(x_test[:,1:])

In [6]:
x_test

array([[ 1.        ,  0.        ,  0.68628299, ..., -0.47730486,
         1.21644716, -0.31056737],
       [ 1.        ,  0.        ,  0.65473611, ..., -0.2622106 ,
         1.15769403, -0.32299092],
       [ 1.        ,  0.        ,  0.03935743, ...,  0.05423083,
         0.5674093 ,  0.07960857],
       ...,
       [ 1.        ,  0.        , -1.32154871, ...,  0.03200803,
         1.21644716, -0.4937042 ],
       [ 1.        ,  0.        , -1.22482534, ...,  0.13320579,
        -0.47231315, -0.16291204],
       [ 1.        ,  0.        , -0.83866695, ..., -1.8354539 ,
        -0.60705146,  0.05494239]])

# Encoding labels

In [3]:
df.rename(columns={'column_ai': 'label'}, inplace=True)
df['label'] = df.label.astype('category')
encoding = {'g': 1, 'b': 0}
df.label.replace(encoding, inplace=True)
df

feature1  feature2  feature3  feature4  feature5  feature6  feature7  \
0           1         0   0.99539  -0.05889   0.85243   0.02306   0.83398   
1           1         0   1.00000  -0.18829   0.93035  -0.36156  -0.10868   
2           1         0   1.00000  -0.03365   1.00000   0.00485   1.00000   
3           1         0   1.00000  -0.45161   1.00000   1.00000   0.71216   
4           1         0   1.00000  -0.02401   0.94140   0.06531   0.92106   
..        ...       ...       ...       ...       ...       ...       ...   
346         1         0   0.83508   0.08298   0.73739  -0.14706   0.84349   
347         1         0   0.95113   0.00419   0.95183  -0.02723   0.93438   
348         1         0   0.94701  -0.00034   0.93207  -0.03227   0.95177   
349         1         0   0.90608  -0.01657   0.98122  -0.01989   0.95691   
350         1         0   0.84710   0.13533   0.73638  -0.06151   0.87873   

     feature8  feature9  feature10  ...  feature26  feature27  feature28  \
0    -0.37708   1.00000    0.03760  ...   -0.51171    0.41078   -0.46168   
1    -0.93597   1.00000   -0.04549  ...   -0.26569   -0.20468   -0.18401   
2    -0.12062   0.88965    0.01198  ...   -0.40220    0.58984   -0.22145   
3    -1.00000   0.00000    0.00000  ...    0.90695    0.51613    1.00000   
4    -0.23255   0.77152   -0.16399  ...   -0.65158    0.13290   -0.53206   
..        ...       ...        ...  ...        ...        ...        ...   
346  -0.05567   0.90441   -0.04622  ...   -0.04202    0.83479    0.00123   
347  -0.01920   0.94590    0.01606  ...    0.01361    0.93522    0.04925   
348  -0.03431   0.95584    0.02446  ...    0.03193    0.92489    0.02542   
349  -0.03646   0.85746    0.00110  ...   -0.02099    0.89147   -0.07760   
350   0.08260   0.88928   -0.09139  ...   -0.15114    0.81147   -0.04822   

     feature29  feature30  feature31  feature32  feature33  feature34  label  
0      0.21266   -0.34090    0.42267   -0.54487    0.18641   -0.45300      1  
1     -0.19040   -0.11593   -0.16626   -0.06288   -0.13738   -0.02447      0  
2      0.43100   -0.17365    0.60436   -0.24180    0.56045   -0.38238      1  
3      1.00000   -0.20099    0.25682    1.00000   -0.32382    1.00000      0  
4      0.02431   -0.62197   -0.05707   -0.59573   -0.04608   -0.65697      1  
..         ...        ...        ...        ...        ...        ...    ...  
346    1.00000    0.12815    0.86660   -0.10714    0.90546   -0.04307      1  
347    0.93159    0.08168    0.94066   -0.00035    0.91483    0.04712      1  
348    0.92120    0.02242    0.92459    0.00442    0.92697   -0.00577      1  
349    0.82983   -0.17238    0.96022   -0.03757    0.87403   -0.16243      1  
350    0.78207   -0.00703    0.75747   -0.06678    0.85764   -0.06151      1  

[351 rows x 35 columns]

# Building Model

In [7]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten

model = Sequential()
model.add(Dense(16,activation = 'relu',input_dim = 34))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(loss='binary_crossentropy',
             optimizer = 'rmsprop',
             metrics = ['accuracy'])

Using TensorFlow backend.
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


# Training Model

In [8]:
hist = model.fit(x_train,y_train , epochs = 110, batch_size=512)


Epoch 1/110
210/210 [==============================] - 0s 662us/step - loss: 1.1156 - accuracy: 0.2524
Epoch 2/110
210/210 [==============================] - 0s 10us/step - loss: 1.0646 - accuracy: 0.2619
Epoch 3/110
210/210 [==============================] - 0s 10us/step - loss: 1.0299 - accuracy: 0.2667
Epoch 4/110
210/210 [==============================] - 0s 19us/step - loss: 1.0020 - accuracy: 0.2667
Epoch 5/110
210/210 [==============================] - 0s 14us/step - loss: 0.9782 - accuracy: 0.2714
Epoch 6/110
210/210 [==============================] - 0s 14us/step - loss: 0.9571 - accuracy: 0.2714
Epoch 7/110
210/210 [==============================] - 0s 14us/step - loss: 0.9381 - accuracy: 0.2905
Epoch 8/110
210/210 [==============================] - 0s 14us/step - loss: 0.9207 - accuracy: 0.3000
Epoch 9/110
210/210 [==============================] - 0s 14us/step - loss: 0.9043 - accuracy: 0.3143
Epoch 10/110
210/210 [==============================] - 0s 14us/step - loss: 0.8

Epoch 79/110
210/210 [==============================] - 0s 24us/step - loss: 0.4110 - accuracy: 0.8667
Epoch 80/110
210/210 [==============================] - 0s 14us/step - loss: 0.4075 - accuracy: 0.8667
Epoch 81/110
210/210 [==============================] - 0s 14us/step - loss: 0.4040 - accuracy: 0.8667
Epoch 82/110
210/210 [==============================] - 0s 14us/step - loss: 0.4006 - accuracy: 0.8667
Epoch 83/110
210/210 [==============================] - 0s 19us/step - loss: 0.3973 - accuracy: 0.8667
Epoch 84/110
210/210 [==============================] - 0s 14us/step - loss: 0.3939 - accuracy: 0.8667
Epoch 85/110
210/210 [==============================] - 0s 14us/step - loss: 0.3906 - accuracy: 0.8667
Epoch 86/110
210/210 [==============================] - 0s 14us/step - loss: 0.3873 - accuracy: 0.8667
Epoch 87/110
210/210 [==============================] - 0s 10us/step - loss: 0.3841 - accuracy: 0.8667
Epoch 88/110
210/210 [==============================] - 0s 14us/step - lo

In [20]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 16)                560       
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 17        
Total params: 577
Trainable params: 577
Non-trainable params: 0
_________________________________________________________________


# Evaluating

In [11]:
scores =model.evaluate(x_test, y_test)
scores
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

141/141 [==============================] - 0s 111us/step
accuracy: 92.20%


# Prediction on Test Data

In [12]:
model.predict(x_test)



array([[0.8943895 ],
       [0.8637259 ],
       [0.76778436],
       [0.8597241 ],
       [0.8094673 ],
       [0.79324067],
       [0.5118331 ],
       [0.9250439 ],
       [0.84335184],
       [0.824691  ],
       [0.85157055],
       [0.35280895],
       [0.1287702 ],
       [0.86152065],
       [0.793431  ],
       [0.02140692],
       [0.01170462],
       [0.39107525],
       [0.06379595],
       [0.8191296 ],
       [0.8247581 ],
       [0.30320168],
       [0.3505027 ],
       [0.26204413],
       [0.70816344],
       [0.87647384],
       [0.18371409],
       [0.43457115],
       [0.8647858 ],
       [0.8029099 ],
       [0.6796166 ],
       [0.70034885],
       [0.2503944 ],
       [0.87285566],
       [0.66906893],
       [0.6866173 ],
       [0.9373125 ],
       [0.426012  ],
       [0.95821893],
       [0.15630966],
       [0.03995118],
       [0.67027354],
       [0.8624816 ],
       [0.23054197],
       [0.05906048],
       [0.808625  ],
       [0.91618854],
       [0.159